version: 0.0
os: linux
files:
 - source: /
   destination: /usr/share/nginx/html/
hooks:
  BeforeInstall:
   - location: delete_files.sh
     timeout: 300
     runas: root
  ApplicationStop:
   - location: stop_nginx.sh
     timeout: 300
     runas: root
  ApplicationStart:
   - location: start_nginx.sh
     timeout: 300
     runas: root