version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 16
  pre_build:
    commands:
     - npm install
  build:
    commands:
     - npm run build
  post_build:
    commands:
     - mv scripts/ build/
     - mv buildspec-2.yml build/
     - mv appspec.yml build/


artifacts:
  files:
   - '**/*'
  base-directory: 'build'
